version: "3.6"

services:
    db:
        container_name: "blog_mysql"
        hostname: db
        image: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
            MYSQL_DATABASE: $DB_DATABASE
            MYSQL_USER: $DB_USERNAME
            MYSQL_PASSWORD: $DB_PASSWORD
        volumes:
            - "./mysql_data:/var/lib/mysql"
#            - "./db-init-scripts:/docker-entrypoint-initdb.d/" если делать миграции через laravel, создавать БД самому не нужно.
        ports:
            - "8001:3306"


    adminer:
        container_name: "blog_adminer"
        image: adminer
        restart: unless-stopped
        ports:
            - "8002:8080"
